### ISSUE TITLE
Receive base_dir as a parameter

### ISSUE THREAD

**Issue by lprone** [madhanl6/ML-Template#1]
This **base_dir** variable could be a parameter to allow running the script easily without changing the code

![image](https://github.com/user-attachments/assets/20f5111c-0430-4626-b934-53b1df8f9c89)

**Comment by madhanl6** [comment]
With this change, if the user runs the script without providing a base directory argument, it will print the usage message and exit with a non-zero status code (1) to indicate an error.

**Comment by madhanl6** [comment]
update the code like this

```bash
def main():
    if len(sys.argv) < 2:
        print("python script.py <base_directory>")
        sys.exit(1)
    
    base_dir = sys.argv[1]
    create_project_structure(base_dir)
```
